// <auto-generated />
namespace ProduceFeeder.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changed2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005110307570_changed-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
